### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Topener** [DanMossa/paliaOnMac-release#16]
Hi! I was wondering if the source code for this is available somewhere. This seems like a great tool that could benefit from actually  being open-source.

**Comment by DanMossa** [comment]
@Topener  Hey! I definitely agree that it would be great if this was open sourced.
My current hesitations are that the code base is extremely gross since I wrote it really quickly in order for it to work.

I also don't want to just open source the code as is and I want it to turn features into micro packages first which will then be released onto here.

It's definitely on my radar and will definitely happen sooner than later!

**Comment by Topener** [comment]
Awesome @DanMossa , looking forward to it. Always a little hesitant to install non-open source software from anywhere :)
