### ISSUE TITLE
not auto updating new patch

### ISSUE THREAD

**Issue by sophiamarieb** [DanMossa/paliaOnMac-release#8]
the game will launch and let me log in but when I click play it says the client is outdated. I've tried pressing update in the launcher and it says the same. Should I uninstall/reinstall? is there a work around to get it to update to the new patch?

**Comment by DanMossa** [comment]
Looking into it now!

**Comment by bookiemel** [comment]
Just wanted to add that I'm also running into this issue (replicable)!

**Comment by DanMossa** [comment]
@sophiamarieb @bookiemel 
I just released 0.5.0: https://github.com/DanMossa/paliaOnMac-release/releases

I'm testing this out now to see if I can fix this issue temporarily. You can download that new version and hit update.
It'll take forever right now since I'm just trying to get it to work. If it ends up working, I can release another update with it being faster. 

Let me know if 0.5.0 works for y'all!

**Comment by renkejr** [comment]
New version is hanging right away on downloading 31/10338.

**Comment by renkejr** [comment]
Went on Palia Discord and clicked Run as you suggested to someone else and I'm in.  So, a file tracking and/or visual bug?

**Comment by DanMossa** [comment]
Fixed bug in 0.5.2. Thank you @renkejr
